# Generated by Django 4.1.4 on 2023-02-11 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('descriptoin', models.TextField(blank=True, null=True)),
                ('price', models.FloatField(default=100)),
            ],
        ),
    ]
