# Generated by Django 4.1.4 on 2023-02-11 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='descriptoin',
        ),
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
